# Options for analysis running.
run:
  timeout: 30s
  go: '1.23'
  modules-download-mode: readonly

# output:
#   format: "checkstyle:out/checkstyle-report.xml,json:stdout,colored-line-number"

linters-settings:
  exhaustive:
    check:
      - switch
      - map
    check-generated: false
    explicit-exhaustive-switch: false
    explicit-exhaustive-map: false
    default-signifies-exhaustive: true
    package-scope-only: false

linters:
  enable:
    # see https://golangci-lint.run/usage/linters for details
    # - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    # - containedctx
    - contextcheck
    # - cyclop
    - decorder
    # - depguard
    # - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    # - execinquery
    - exhaustive
    # - exhaustruct
    # - exportloopref
    - forbidigo
    - forcetypeassert
    # - funlen
    - gocheckcompilerdirectives
    # - gochecknoglobals
    # - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    # - godot
    # - godox
    # - goerr113
    - gofmt
    # - gofumpt
    - goheader
    - goimports
    # - gomnd
    - gomoddirectives
    # - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    # - gosmopolitan
    - govet
    - grouper
    # - importas
    - ineffassign
    # - interfacebloat
    # - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    # - misspell
    # - musttag
    - nakedret
    - nestif
    # - nilerr
    - nilnil
    # - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    # - paralleltest
    - prealloc
    - predeclared
    # - promlinter
    - reassign
    - revive
    # - rowserrcheck
    # - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    # - tagliatelle
    - tenv
    - testableexamples
    # - testpackage
    - thelper
    # - tparallel
    - typecheck
    - unconvert
    # - unparam
    - unused
    - usestdlibvars
    # - varnamelen
    - wastedassign
    - whitespace
    # - wrapcheck
    # - wsl
    # - zerologlint

issues:
  # See the dedicated "issues" documentation section.
  exclude-generated: lax

severity:
  # See the dedicated "severity" documentation section.
  default-severity: error
